Bug #2 Symptom: Running App in IDE:
A) receive many errors such as : [EL Warning]: metadata: 2025-03-21 13:59:59.437--ServerSession(1844736085)--Thread(Thread[#24,AWT-EventQueue-0,6,main])--The edu.touro.mco152.bm.ui.SelectFrame$1 class was compiled with an unsupported JDK. Report this error to the EclipseLink open source project.
java.lang.IllegalArgumentException: Unsupported class file major version 66
[EL Severe]: metadata: 2025-03-21 13:59:59.437--ServerSession(1844736085)--Thread(Thread[#24,AWT-EventQueue-0,6,main])--The edu.touro.mco152.bm.ui.SelectFrame$1 class was compiled with an unsupported JDK. Report this error to the EclipseLink open source project.
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 0

B) as program starts to connect to DB, fails with: [EL Fine]: connection: 2025-03-21 14:00:00.146--ServerSession(1844736085)--Thread(Thread[#24,AWT-EventQueue-0,6,main])--/file:/C:/LCM/MCO152_Meth/studentProjs/2025Spring/autobuild/_attias/lcmbadbm/lib/build/classes/java/main/_jDiskMarkPU login successful
[EL Warning]: metamodel: 2025-03-21 14:00:00.163--Thread(Thread[#24,AWT-EventQueue-0,6,main])--The collection of metamodel types is empty. Model classes may not have been found during entity search for Java SE and some Java EE container managed persistence units.  Please verify that your entity classes are referenced in persistence.xml using either <class> elements or a global <exclude-unlisted-classes>false</exclude-unlisted-classes> element
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: NamedQuery of name: DiskRun.findAll not found.
	at org.eclipse.persistence.internal.jpa.QueryImpl.getDatabaseQueryInternal(QueryImpl.java:364)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createNamedQuery(EntityManagerImpl.java:1244)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createNamedQuery(EntityManagerImpl.java:1265)
	at edu.touro.mco152.bm.persist.DiskRun.findAll(DiskRun.java:87)

Diag: warnings/errors about EclipseLink indicate wrong versions.

Student failed to follow instructions from Slack, March 1st, about eclipselink versions

Change to newer 4.0.5 version of eclipselink, remove persistence-api dependency statement.

With this fix program starts OK in IDE. Will still fail when ran from jar/command line for other reasons.